spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: zh-ai-agent
  ai:
    dashscope:
      api-key: 'sk-280dabc277984bf7a8561011f7e3bf8c'

server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi 配置
springdoc:
  swagger-ui:
    path: /docs.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zhou.zhaiagent.controller
